apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wombat-python 
  janus-idp.io/tekton: wombat-python
  backstage.io/kubernetes-id: wombat-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wombat-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  